on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    name: Deploy Bruce
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      #- name: Kill the old Bruce
      #  run: 

      - name: Launch Bruce
        timeout-minutes: 1
        continue-on-error: true
        run: /home/pi/Desktop/run_bruce.sh
