on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    name: Deploy Bruce
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      #- name: Kill the old Bruce
      #  run: 

      - name: Launch Bruce
        run: /home/pi/bruce.sh
